{% set name = "httpx" %}
{% set version = "0.12.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 405b4749f597b1f45cae5bffc17b23dc251cce30a0c4c8126f1007b9e728a615

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - certifi
    - chardet ==3.*
    - h11 >=0.8,<0.10
    - h2 ==3.*
    - hstspreload
    - idna ==2.*
    - python
    - rfc3986 >=1.3,<2
    - sniffio ==1.*
    - urllib3 ==1.*

test:
  imports:
    - httpx
    - httpx/_backends
    - httpx/_dispatch
  requires:
    - pytest
  commands:
    - pytest --pyargs sixtools.tests

about:
  home: "https://github.com/encode/httpx"
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: "The next generation HTTP client."
