{% set name = "httpx" %}
{% set version = "0.18.2" %}
{% set sha256 = "9f99c15d33642d38bce8405df088c1c4cfd940284b4290cacbfb02e64f4877c6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - certifi
    - httpcore >=0.13
    - idna ==2.*
    - rfc3986 >=1.3,<2
    - sniffio

test:
  imports:
    - httpx
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/encode/httpx
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: A next-generation HTTP client for Python.
  doc_url: https://www.encode.io/httpx/
  dev_url: https://github.com/encode/httpx
